name: React build
on:
    push: # master Branch에서 push 이벤트가 일어났을 때만 실행
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout source code. # 레포지토리 체크아웃
              uses: actions/checkout@master

            - name: Install Dependencies # 의존 파일 설치
              working-directory: front
              run: npm install

            - name: Build # React Build
              working-directory: front
              run: npm run build

            - name: Deploy # S3에 배포하기
              working-directory: front
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 cp --recursive --region us-east-1 build s3://catchroom-github-action-tuto
